---
title: "Problem B.2"
author: "Haonan LI"
date: "2025-03-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
# Problem B.2

# (a)
data("USArrests")
head(USArrests)

# Compute the Euclidean distance
dist_USArrests <- dist(USArrests, method = "euclidean")

# function for hierarchical clustering
hc.complete <- hclust(dist_USArrests, method = "complete")

# Tree diagrams
plot(hc.complete, 
     main = "Hierarchical Clustering with Complete Linkage", 
     xlab = "", 
     sub = "", 
     cex = 0.6)

# (b)
# Clipping the dendrogram into 3 clusters
clusters <- cutree(hc.complete, k = 3)

# Which states belong to which clusters
cluster_assignments <- split(rownames(USArrests), clusters)
cluster_assignments

# (c)
# Standardized data
USArrests.scaled <- scale(USArrests)

# Compute Euclidean distance matrix and perform hierarchical clustering
dist_scaled <- dist(USArrests.scaled, method = "euclidean")   
hc.complete.scaled <- hclust(dist_scaled, method = "complete") 

# Tree diagrams
plot(hc.complete.scaled, 
main = "Hierarchical Clustering with Complete Linkage (Scaled Data)", 
xlab = "", 
sub = "", 
cex = 0.6)


#(d)
# Scaling the data ensures that each variable 
# contributes more evenly to the distance calculation,
# making the hierarchical clustering result better reflect 
# the underlying structure of the data.
# Therefore, in most cases, when there are 
# differences in the scale or range of variables, 
# the data should be standardized before calculating the dissimilarities.

```

